name: Netch Release CI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: C++
        uses: msys2/setup-msys2@v2

      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 -Configuration Release -OutputPath release

      - name: Package
        shell: pwsh
        run: |
          7z a -mx9 Netch.7z release
          7z rn Netch.7z release Netch

      - name: Checksum
        shell: pwsh
        run: |
          $hash=(Get-FileHash Netch.7z -Algorithm SHA256).Hash.ToLower()
          echo "$hash Netch.7z"
          echo "NETCH_SHA256=$hash" | Out-File -Append -Encoding UTF8 -FilePath $Env:GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{ contains(github.ref, '-') }}
          draft: false
          files: |
            Netch.7z
          body: |
            [![](https://img.shields.io/badge/Telegram-Channel-blue)](https://t.me/netch_channel) [![](https://img.shields.io/badge/Telegram-Group-green)](https://t.me/netch_group)
            ## Changelogs
            * This is an automated deployment of GitHub Actions, the change log should be updated manually soon
            
            ## 更新日志
            * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新

            ## 校验和
            | 文件名 | SHA256 |
            | :- | :- |
            | Netch.7z | ${{ env.Netch_SHA256 }} |
