name: Netch Release
on:
  push:
    tags:
    - '*.*'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - name: Binaries Repo LFS Pull
      working-directory: binaries
      run: git lfs pull

    - name: Build Solution
      shell: pwsh
      run: .\BUILD.ps1

    - name: Package
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
        7z a -mx9 C:\builtfiles\Netch.7z .\Netch\bin\Publish\
        7z rn C:\builtfiles\Netch.7z Publish Netch
        echo "Netch_SHA256=$(.\GetSHA256.ps1 C:\builtfiles\Netch.7z)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Netch_EXE_SHA256=$(.\GetSHA256.ps1 Netch\bin\Publish\Netch.exe)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        prerelease: ${{ contains(github.ref, '-') }}
        draft: false
        files: |
          C:\builtfiles\Netch.7z
        body: |
          [![](https://img.shields.io/badge/Telegram-Channel-blue)](https://t.me/Netch) [![](https://img.shields.io/badge/Telegram-Group-green)](https://t.me/Netch_Discuss_Group)

          ## 更新日志
          * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新

          ## 校验和
          | 文件名 | SHA256 |
          | :- | :- |
          | Netch.7z | ${{ env.Netch_SHA256 }} |
